if(NOT DEFINED JANUS)
    message(FATAL_ERROR "JANUS is required")
endif()
if(NOT DEFINED WORK_DIR)
    message(FATAL_ERROR "WORK_DIR is required")
endif()

file(MAKE_DIRECTORY "${WORK_DIR}")

set(risky_source "${WORK_DIR}/risky.janus")
file(WRITE "${risky_source}" "def main() : int {\n    var x : int = 1\n    while x < 100 {\n        x = 3 * x + 1\n    }\n    return 0\n}\n")

set(risky_right_source "${WORK_DIR}/risky_right.janus")
file(WRITE "${risky_right_source}" "def main() : int {\n    var x : int = 1\n    while x < 100 {\n        x = x * 2\n    }\n    return x\n}\n")

set(risky_square_source "${WORK_DIR}/risky_square.janus")
file(WRITE "${risky_square_source}" "def main() : int {\n    var x : int = 2\n    while x < 100 {\n        x = x * x\n    }\n    return x\n}\n")

set(simple_source "${WORK_DIR}/simple.janus")
file(WRITE "${simple_source}" "def main() : int {\n    var i : int = 0\n    while i < 10 {\n        i = i + 1\n    }\n    return i\n}\n")

set(zero_source "${WORK_DIR}/zero.janus")
file(WRITE "${zero_source}" "def main() : int {\n    var x : int = 1\n    while x < 10 {\n        x = x * 0\n    }\n    return x\n}\n")

set(zero_left_source "${WORK_DIR}/zero_left.janus")
file(WRITE "${zero_left_source}" "def main() : int {\n    var x : int = 1\n    while x < 10 {\n        x = 0 * x\n    }\n    return x\n}\n")

set(one_source "${WORK_DIR}/one.janus")
file(WRITE "${one_source}" "def main() : int {\n    var x : int = 1\n    while x < 10 {\n        x = x * 1\n    }\n    return x\n}\n")

set(one_left_source "${WORK_DIR}/one_left.janus")
file(WRITE "${one_left_source}" "def main() : int {\n    var x : int = 1\n    while x < 10 {\n        x = 1 * x\n    }\n    return x\n}\n")

set(one_add_source "${WORK_DIR}/one_add.janus")
file(WRITE "${one_add_source}" "def main() : int {\n    var x : int = 1\n    while x < 10 {\n        x = x * 1 + 1\n    }\n    return x\n}\n")

set(unknown_factor_source "${WORK_DIR}/unknown_factor.janus")
file(WRITE "${unknown_factor_source}" "def main() : int {\n    var x : int = 1\n    var k : int = 2\n    while x < 10 {\n        x = x * k\n    }\n    return x\n}\n")

set(outside_source "${WORK_DIR}/outside.janus")
file(WRITE "${outside_source}" "def main() : int {\n    var x : int = 1\n    x = x * 3\n    return x\n}\n")

set(non_self_source "${WORK_DIR}/non_self.janus")
file(WRITE "${non_self_source}" "def main() : int {\n    var x : int = 1\n    var y : int = 2\n    while x < 10 {\n        x = y * 3\n        x = x + 1\n    }\n    return x\n}\n")

set(invalid_source "${WORK_DIR}/invalid.janus")
file(WRITE "${invalid_source}" "def main() : int {\n    var x : int = 1\n    while x < 10 {\n        x = 3 * x + 1\n    }\n    return missing\n}\n")

function(run_janus name)
    execute_process(
        COMMAND "${JANUS}" ${ARGN}
        RESULT_VARIABLE result
        OUTPUT_VARIABLE output
        ERROR_VARIABLE error
    )
    set("${name}_RESULT" "${result}" PARENT_SCOPE)
    set("${name}_OUTPUT" "${output}" PARENT_SCOPE)
    set("${name}_ERROR" "${error}" PARENT_SCOPE)
    string(CONCAT combined "${output}" "${error}")
    set("${name}_COMBINED" "${combined}" PARENT_SCOPE)
endfunction()

run_janus(no_flag check "${risky_source}")
if(NOT no_flag_RESULT EQUAL 0)
    message(FATAL_ERROR "risky source failed without flag:\n${no_flag_COMBINED}")
endif()
if(no_flag_COMBINED MATCHES "warning:|overflow|time budget")
    message(FATAL_ERROR "risky source emitted diagnostics without flag:\n${no_flag_COMBINED}")
endif()

run_janus(warn_check check "${risky_source}" --warn-high-growth-loops)
if(NOT warn_check_RESULT EQUAL 0)
    message(FATAL_ERROR "risky source failed with warning flag:\n${warn_check_COMBINED}")
endif()
if(NOT warn_check_COMBINED MATCHES "risky\\.janus:4:9: warning: high-growth loop")
    message(FATAL_ERROR "warning does not point at the risky assignment line/column:\n${warn_check_COMBINED}")
endif()
if(NOT warn_check_COMBINED MATCHES "overflow")
    message(FATAL_ERROR "warning does not mention overflow risk:\n${warn_check_COMBINED}")
endif()
if(NOT warn_check_COMBINED MATCHES "time budget")
    message(FATAL_ERROR "warning does not suggest a time budget:\n${warn_check_COMBINED}")
endif()

run_janus(warn_check_flag_first check --warn-high-growth-loops "${risky_source}")
if(NOT warn_check_flag_first_RESULT EQUAL 0)
    message(FATAL_ERROR "check rejected warning flag before source:\n${warn_check_flag_first_COMBINED}")
endif()
if(NOT warn_check_flag_first_COMBINED MATCHES "warning: high-growth loop")
    message(FATAL_ERROR "check with flag before source did not warn:\n${warn_check_flag_first_COMBINED}")
endif()

run_janus(risky_right check "${risky_right_source}" --warn-high-growth-loops)
if(NOT risky_right_RESULT EQUAL 0)
    message(FATAL_ERROR "risky right-literal source failed:\n${risky_right_COMBINED}")
endif()
if(NOT risky_right_COMBINED MATCHES "warning: high-growth loop")
    message(FATAL_ERROR "x * 2 did not produce a warning:\n${risky_right_COMBINED}")
endif()

run_janus(risky_square check "${risky_square_source}" --warn-high-growth-loops)
if(NOT risky_square_RESULT EQUAL 0)
    message(FATAL_ERROR "risky square source failed:\n${risky_square_COMBINED}")
endif()
if(NOT risky_square_COMBINED MATCHES "warning: high-growth loop")
    message(FATAL_ERROR "x * x did not produce a warning:\n${risky_square_COMBINED}")
endif()

run_janus(simple check "${simple_source}" --warn-high-growth-loops)
if(NOT simple_RESULT EQUAL 0)
    message(FATAL_ERROR "simple induction source failed:\n${simple_COMBINED}")
endif()
if(simple_COMBINED MATCHES "warning:")
    message(FATAL_ERROR "simple induction loop produced a warning:\n${simple_COMBINED}")
endif()

foreach(case zero zero_left one one_left one_add unknown_factor)
    run_janus("${case}" check "${${case}_source}" --warn-high-growth-loops)
    if(NOT ${case}_RESULT EQUAL 0)
        message(FATAL_ERROR "${case} source failed:\n${${case}_COMBINED}")
    endif()
    if(${case}_COMBINED MATCHES "warning:")
        message(FATAL_ERROR "${case} source produced a warning:\n${${case}_COMBINED}")
    endif()
endforeach()

run_janus(outside check "${outside_source}" --warn-high-growth-loops)
if(NOT outside_RESULT EQUAL 0)
    message(FATAL_ERROR "outside-loop source failed:\n${outside_COMBINED}")
endif()
if(outside_COMBINED MATCHES "warning:")
    message(FATAL_ERROR "outside-loop multiplication produced a warning:\n${outside_COMBINED}")
endif()

run_janus(non_self check "${non_self_source}" --warn-high-growth-loops)
if(NOT non_self_RESULT EQUAL 0)
    message(FATAL_ERROR "non-self source failed:\n${non_self_COMBINED}")
endif()
if(non_self_COMBINED MATCHES "warning:")
    message(FATAL_ERROR "non-self multiplication produced a warning:\n${non_self_COMBINED}")
endif()

run_janus(invalid check "${invalid_source}" --warn-high-growth-loops)
if(invalid_RESULT EQUAL 0)
    message(FATAL_ERROR "invalid source unexpectedly succeeded")
endif()
if(NOT invalid_COMBINED MATCHES "error:")
    message(FATAL_ERROR "invalid source did not keep compile error:\n${invalid_COMBINED}")
endif()

run_janus(warn_build build "${risky_source}" --warn-high-growth-loops -o "${WORK_DIR}/risky-bin")
if(NOT warn_build_RESULT EQUAL 0)
    message(FATAL_ERROR "build rejected warning flag:\n${warn_build_COMBINED}")
endif()
if(NOT warn_build_COMBINED MATCHES "warning: high-growth loop")
    message(FATAL_ERROR "build did not emit high-growth warning:\n${warn_build_COMBINED}")
endif()

run_janus(warn_build_flag_first build --warn-high-growth-loops "${risky_source}" -o "${WORK_DIR}/risky-bin-flag-first")
if(NOT warn_build_flag_first_RESULT EQUAL 0)
    message(FATAL_ERROR "build rejected warning flag before source:\n${warn_build_flag_first_COMBINED}")
endif()
if(NOT warn_build_flag_first_COMBINED MATCHES "warning: high-growth loop")
    message(FATAL_ERROR "build with flag before source did not emit high-growth warning:\n${warn_build_flag_first_COMBINED}")
endif()

run_janus(warn_build_emit build --warn-high-growth-loops "${risky_source}" --emit llvm-ir -o "${WORK_DIR}/risky.ll")
if(NOT warn_build_emit_RESULT EQUAL 0)
    message(FATAL_ERROR "build rejected warning flag before source with --emit/-o:\n${warn_build_emit_COMBINED}")
endif()
if(NOT warn_build_emit_COMBINED MATCHES "warning: high-growth loop")
    message(FATAL_ERROR "build with --emit/-o did not emit high-growth warning:\n${warn_build_emit_COMBINED}")
endif()
if(NOT EXISTS "${WORK_DIR}/risky.ll")
    message(FATAL_ERROR "build with --emit/-o did not create output")
endif()

run_janus(warn_run run "${risky_source}" --warn-high-growth-loops)
if(NOT warn_run_RESULT EQUAL 0)
    message(FATAL_ERROR "run rejected warning flag:\n${warn_run_COMBINED}")
endif()
if(NOT warn_run_COMBINED MATCHES "warning: high-growth loop")
    message(FATAL_ERROR "run did not emit high-growth warning:\n${warn_run_COMBINED}")
endif()

run_janus(warn_run_flag_first run --warn-high-growth-loops "${risky_source}")
if(NOT warn_run_flag_first_RESULT EQUAL 0)
    message(FATAL_ERROR "run rejected warning flag before source:\n${warn_run_flag_first_COMBINED}")
endif()
if(NOT warn_run_flag_first_COMBINED MATCHES "warning: high-growth loop")
    message(FATAL_ERROR "run with flag before source did not emit high-growth warning:\n${warn_run_flag_first_COMBINED}")
endif()

run_janus(multiple_sources check "${risky_source}" "${simple_source}" --warn-high-growth-loops)
if(multiple_sources_RESULT EQUAL 0)
    message(FATAL_ERROR "multiple sources unexpectedly succeeded")
endif()

run_janus(fmt_rejects fmt "${risky_source}" --warn-high-growth-loops)
if(fmt_rejects_RESULT EQUAL 0)
    message(FATAL_ERROR "fmt accepted --warn-high-growth-loops")
endif()

run_janus(test_rejects test --warn-high-growth-loops)
if(test_rejects_RESULT EQUAL 0)
    message(FATAL_ERROR "test accepted --warn-high-growth-loops")
endif()

run_janus(help --help)
if(NOT help_RESULT EQUAL 0)
    message(FATAL_ERROR "janus --help failed:\n${help_COMBINED}")
endif()
if(NOT help_COMBINED MATCHES "--warn-high-growth-loops")
    message(FATAL_ERROR "help does not document --warn-high-growth-loops:\n${help_COMBINED}")
endif()
