#include "janus/driver/dependency.hpp"

#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <stdexcept>
#include <string>
#include <vector>

#ifndef _WIN32
#include <sys/wait.h>
#endif

namespace {

std::string shell_quote(const std::filesystem::path &path) {
  const std::string value = path.string();
#ifdef _WIN32
  std::string quoted{"\""};
  for (const char character : value) {
    if (character == '"')
      quoted += '\\';
    quoted += character;
  }
  return quoted + '"';
#else
  std::string quoted{"'"};
  for (const char character : value) {
    if (character == '\'')
      quoted += "'\\''";
    else
      quoted += character;
  }
  return quoted + '\'';
#endif
}

int command_status(int status) {
  if (status == -1)
    return 1;
#ifdef _WIN32
  return status;
#else
  if (WIFEXITED(status))
    return WEXITSTATUS(status);
  return 1;
#endif
}

void run(const std::string &command, const std::string &description) {
  if (command_status(std::system(command.c_str())) != 0)
    throw std::runtime_error{description};
}

std::filesystem::path resolve_git(const janus::driver::Manifest &manifest,
                                  const janus::driver::Dependency &dependency) {
  const std::filesystem::path cache =
      manifest.root() / "target/dependencies" /
      (dependency.name + "-" + dependency.revision.substr(0, 12));
  const std::filesystem::path revision_file = cache / ".janus-revision";
  if (std::filesystem::exists(cache)) {
    std::ifstream input{revision_file};
    std::string cached_revision;
    input >> cached_revision;
    if (cached_revision != dependency.revision)
      throw std::runtime_error{"cached dependency '" + dependency.name +
                               "' has an unexpected revision"};
  } else {
    const std::filesystem::path staging = cache.string() + ".new";
    std::filesystem::create_directories(staging.parent_path());
    std::filesystem::remove_all(staging);
    try {
      run("git clone --quiet --no-checkout " + shell_quote(dependency.git) +
              " " + shell_quote(staging),
          "could not clone dependency '" + dependency.name + "'");
      run("git -C " + shell_quote(staging) + " checkout --quiet --detach " +
              shell_quote(dependency.revision),
          "could not check out dependency '" + dependency.name + "' at " +
              dependency.revision);
      std::ofstream revision{staging / ".janus-revision"};
      revision << dependency.revision << '\n';
      revision.close();
      std::filesystem::rename(staging, cache);
    } catch (...) {
      std::error_code ignored;
      std::filesystem::remove_all(staging, ignored);
      throw;
    }
  }
  return cache;
}

void validate_dependency(const janus::driver::Dependency &dependency,
                         const std::filesystem::path &root) {
  const janus::driver::Manifest dependency_manifest =
      janus::driver::load_manifest(root / "janus.toml");
  if (dependency_manifest.name != dependency.name)
    throw std::runtime_error{"dependency '" + dependency.name +
                             "' declares package name '" +
                             dependency_manifest.name + "'"};
  if (!std::filesystem::is_directory(root / "src"))
    throw std::runtime_error{"dependency '" + dependency.name +
                             "' has no src directory"};
}

} // namespace

namespace janus::driver {

std::vector<std::filesystem::path>
resolve_dependencies(const Manifest &manifest) {
  std::vector<std::filesystem::path> search_paths;
  std::string lock = "# Generated by Janus. Do not edit.\nversion = 1\n";
  for (const Dependency &dependency : manifest.dependencies) {
    const std::filesystem::path root =
        dependency.is_git()
            ? resolve_git(manifest, dependency)
            : (manifest.root() / dependency.path).lexically_normal();
    if (!std::filesystem::is_directory(root))
      throw std::runtime_error{"dependency '" + dependency.name +
                               "' does not exist at '" + root.string() + "'"};
    validate_dependency(dependency, root);
    search_paths.push_back(root / "src");

    lock += "\n[[dependency]]\nname = \"" + dependency.name + "\"\n";
    if (dependency.is_git()) {
      lock += "source = \"git+" + dependency.git + "\"\n";
      lock += "revision = \"" + dependency.revision + "\"\n";
    } else {
      lock += "source = \"path+" + dependency.path.generic_string() + "\"\n";
      const Manifest dependency_manifest = load_manifest(root / "janus.toml");
      lock += "version = \"" + dependency_manifest.version + "\"\n";
    }
  }
  const std::filesystem::path lock_path = manifest.root() / "janus.lock";
  const std::filesystem::path temporary = manifest.root() / "janus.lock.new";
  {
    std::ofstream output{temporary, std::ios::trunc};
    if (!output)
      throw std::runtime_error{"cannot write janus.lock"};
    output << lock;
  }
  std::error_code ignored;
  std::filesystem::remove(lock_path, ignored);
  std::filesystem::rename(temporary, lock_path);
  return search_paths;
}

} // namespace janus::driver
