#!/usr/bin/env python3
"""Generate the explicit call-capability/effect overload matrix for #313."""
from itertools import product
from pathlib import Path
import argparse
import re

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / 'stdlib/std/functional.janus'
MARKER = '// BEGIN CLOSURE FACTORIES'
CAPS = ('Fn', 'FnMut', 'FnOnce')


def function(cap, pure, arguments, result):
    return f"{'pure ' if pure else ''}{cap} ({arguments}) => {result}"


def generate():
    base = TARGET.read_text(encoding='utf-8').split(MARKER)[0].replace('\nimport std.option\n', '').replace('\nimport std.option.{OptionPair}\n', '')
    base = base.replace('module std.functional\n', 'module std.functional\n\nimport std.option.{OptionPair}\n')
    base = re.sub(r'\n{3,}', '\n\n', base)
    text = base.rstrip() + '\n\n' + MARKER + '\n'
    text += '// Generated by scripts/generate_functional_factories.py; edit the generator.\n'
    text += '''
private struct CompositionState[Outer, Inner](var outer : Outer, var inner : Inner) {}
private struct PartialState[Callback, First](var function : Callback, val first : First) {}
'''
    for po, pi in product(range(2), repeat=2):
        outer = function('FnOnce', po, 'B', 'C')
        inner = function('FnOnce', pi, 'A', 'B')
        text += f'''
private {'pure ' if po and pi else ''}def applyComposition{po}{pi}[A, B, C](value : A, outer : {outer}, inner : {inner}) : C {{
    val outerCallback : {outer} = move outer
    defer delete outerCallback
    val innerCallback : {inner} = move inner
    defer delete innerCallback
    return outerCallback(innerCallback(move value))
}}
'''
    for pure in range(2):
        callback = function('FnOnce', pure, 'A, B', 'C')
        text += f'''
private {'pure ' if pure else ''}def applyPartial{pure}[A, B, C](function : {callback}, first : A, second : B) : C {{
    val callback : {callback} = move function
    defer delete callback
    return callback(move first, move second)
}}
'''
    for i, j, po, pi in product(range(3), range(3), range(2), range(2)):
        cap = CAPS[max(i, j)]
        outer = function(CAPS[i], po, 'B', 'C')
        inner = function(CAPS[j], pi, 'A', 'B')
        result = function(cap, po and pi, 'A', 'C')
        state = f'CompositionState[{outer}, {inner}]'
        if cap == 'FnOnce':
            body = f'''return match move state {{
            CompositionState(outerCallback, innerCallback) => applyComposition{po}{pi}[A, B, C](move value, move outerCallback, move innerCallback)
        }}'''
        else:
            body = f'''borrow {'var' if i else 'val'} outerCallback : {outer} = state.outer
        borrow {'var' if j else 'val'} innerCallback : {inner} = state.inner
        return outerCallback(innerCallback(move value))'''
        text += f'''
/// Construit une composition propriétaire, `inner` avant `outer`.
/// @param outer Seconde transformation, transférée une fois.
/// @param inner Première transformation, transférée une fois.
/// @return Closure `{cap}` ; détruire les résultats réutilisables avec `defer delete`.
def compose[A, B, C](outer : {outer}, inner : {inner}) : {result} {{
    {'var' if cap == 'FnMut' else 'val'} state = new {state}(move outer, move inner)
    return owningCapture[{state}](state, (value : A) => {{
        {body}
    }})
}}

/// Construit une composition propriétaire dans l'ordre de lecture.
/// @param first Première transformation, transférée une fois.
/// @param after Seconde transformation, transférée une fois.
/// @return Closure `{cap}` ; même contrat de nettoyage que `compose`.
def andThen[A, B, C](first : {inner}, after : {outer}) : {result} {{
    return compose[A, B, C](move after, move first)
}}
'''
    for i, pure, copy in product(range(3), range(2), range(2)):
        cap = CAPS[i] if copy else 'FnOnce'
        effect = pure and copy
        constraint = ' <: Copy' if copy else ''
        callback = function(CAPS[i], pure, 'A, B', 'C')
        result = function(cap, effect, 'B', 'C')
        state = f'PartialState[{callback}, A]'
        if cap == 'FnOnce':
            body = f'''return match move state {{
            PartialState(callback, fixed) => applyPartial{pure}[A, B, C](move callback, move fixed, move second)
        }}'''
        else:
            body = f'''borrow {'var' if i else 'val'} callback : {callback} = state.function
        return callback(state.first, move second)'''
        text += f'''
/// Fixe le premier argument, évalué une fois pendant la construction.
/// @param function Callback binaire propriétaire.
/// @param first Valeur fixée ; un propriétaire exige un `move` explicite.
/// @return Closure `{cap}`, possédant un seul environnement supplémentaire.
def partialFirst2[A{constraint}, B, C](function : {callback}, first : A) : {result} {{
    {'var' if cap == 'FnMut' else 'val'} state = new {state}(move function, move first)
    return owningCapture[{state}](state, (second : B) => {{
        {body}
    }})
}}

/// Transfère une fonction binaire vers deux applications explicites.
/// @param function Callback transférée à l'application partielle lors du premier appel.
/// @return Closure affine produisant une closure `{cap}` ; aucun clonage de callback.
def curry2[A{constraint}, B, C](function : {callback}) : {function('FnOnce', effect, 'A', result)} {{
    return owningCapture[{callback}](function, (first : A) => {{
        {'var' if cap == 'FnMut' else 'val'} state = new {state}(move function, move first)
        val result : {result} = owningCapture[{state}](state, (second : B) => {{
            {body}
        }})
        return move result
    }})
}}
'''
    for i, j, po, pi, copy in product(range(3), range(3), range(2), range(2), range(2)):
        if copy and not (po and pi):
            continue
        # Each call creates a fresh inner callback, so only the outer capability
        # limits reuse. Destructuring consumes both fields, with no pair clone.
        cap = CAPS[i]
        inner = function(CAPS[j], pi, 'B', 'C')
        callback = function(cap, po, 'A', inner)
        pure = po and pi and copy
        result = function(cap, pure, 'OptionPair[A, B]', 'C')
        mode = ('borrow ' if i == 0 else 'borrow var ' if i == 1 else '')
        call_arg = 'move function' if i == 2 else 'function'
        name = f'applyUncurried{i}{j}{po}{pi}{copy}'
        constraint = ' <: Copy' if copy else ''
        # Pure helpers use an owned local to make callback destruction explicit.
        local = f'val callback : {callback} = move function\n    defer delete callback\n    ' if i == 2 else ''
        callee = 'callback' if i == 2 else 'function'
        body = f"""val next : {inner} = {callee}(move left)
    defer delete next
    return next(move right)""" if pure else f"""val finish = owningCapture[B](right, (next : {inner}) => {{
        val innerCallback : {inner} = move next
        defer delete innerCallback
        return innerCallback(move right)
    }})
    defer delete finish
    return finish({callee}(move left))"""
        text += f'''
private {'pure ' if pure else ''}def {name}[A, B{constraint}, C]({mode}function : {callback}, left : A, right : B) : C {{
    {local}{body}
}}

/// Applique une fonction curryfiée à la paire canonique `OptionPair`.
/// @param function Callback propriétaire produisant la seconde étape.
/// @return Closure `{cap}`, consommant les champs de la paire de gauche à droite.
def uncurry2[A, B{constraint}, C](function : {callback}) : {result} {{
    return owningCapture[{callback}](function, (pair : OptionPair[A, B]) => {{
        return match move pair {{
            OptionPair(left, right) => {name}[A, B, C]({call_arg}, move left, move right)
        }}
    }})
}}
'''
    return text


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    expected = generate()
    if args.check:
        if TARGET.read_text(encoding='utf-8') != expected:
            parser.exit(1, 'functional factories are stale; run this generator\n')
    else:
        TARGET.write_text(expected, encoding='utf-8', newline='\n')


if __name__ == '__main__':
    main()
