#!/usr/bin/env python3
"""Generate the compact Unicode tables used by the Janus lexer.

The checked-in output makes identifier behaviour independent from Python and
the host locale.  Regenerate it deliberately when updating the Unicode version.
"""

from pathlib import Path
import unicodedata


EXPECTED_UNICODE_VERSION = "16.0.0"
OUTPUT = Path(__file__).resolve().parents[1] / "src/frontend/unicode_identifier_tables.inc"


def ranges(values):
    result = []
    start = previous = None
    for value in values:
        if start is None:
            start = previous = value
        elif value == previous + 1:
            previous = value
        else:
            result.append((start, previous))
            start = previous = value
    if start is not None:
        result.append((start, previous))
    return result


def emit_ranges(name, values):
    entries = ",\n".join(f"  {{{a:#x}, {b:#x}}}" for a, b in ranges(values))
    return f"constexpr CodePointRange {name}[] = {{\n{entries}\n}};\n"


def main():
    if unicodedata.unidata_version != EXPECTED_UNICODE_VERSION:
        raise SystemExit(
            f"expected Unicode {EXPECTED_UNICODE_VERSION}, got {unicodedata.unidata_version}"
        )

    scalars = range(0x110000)
    starts = [cp for cp in scalars if cp != 0x5F and chr(cp).isidentifier()]
    continues = [cp for cp in scalars if ("A" + chr(cp)).isidentifier()]

    decompositions = []
    combining = []
    compositions = []
    for cp in range(0x110000):
        character = chr(cp)
        ccc = unicodedata.combining(character)
        if ccc:
            combining.append((cp, ccc))
        raw = unicodedata.decomposition(character)
        if raw and not raw.startswith("<"):
            parts = tuple(int(part, 16) for part in raw.split())
            decompositions.append((cp, parts))
            if len(parts) == 2 and unicodedata.normalize("NFC", "".join(map(chr, parts))) == character:
                compositions.append((parts[0], parts[1], cp))
    compositions.sort()

    flat_parts = []
    decomposition_rows = []
    for cp, parts in decompositions:
        offset = len(flat_parts)
        flat_parts.extend(parts)
        decomposition_rows.append((cp, offset, len(parts)))

    lines = [
        "// Generated by scripts/generate_unicode_identifier_tables.py; do not edit.",
        "// Derived from Unicode data distributed under Unicode-3.0; see NOTICE.",
        f'constexpr std::string_view kUnicodeVersion = "{EXPECTED_UNICODE_VERSION}";',
        emit_ranges("kXidStart", starts),
        emit_ranges("kXidContinue", continues),
        "constexpr char32_t kDecompositionScalars[] = {\n  "
        + ", ".join(f"{cp:#x}" for cp in flat_parts)
        + "\n};",
        "constexpr Decomposition kDecompositions[] = {\n"
        + ",\n".join(f"  {{{cp:#x}, {offset}, {length}}}" for cp, offset, length in decomposition_rows)
        + "\n};",
        "constexpr CombiningClass kCombiningClasses[] = {\n"
        + ",\n".join(f"  {{{cp:#x}, {ccc}}}" for cp, ccc in combining)
        + "\n};",
        "constexpr Composition kCompositions[] = {\n"
        + ",\n".join(f"  {{{first:#x}, {second:#x}, {result:#x}}}" for first, second, result in compositions)
        + "\n};",
    ]
    OUTPUT.write_text("\n\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
